version = 1

exclude_patterns = [
  "**/intTest/**",
  "spring-boot-tests/**"
]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "ruby"